export const queryKeys = {
  dashboard: ["dashboard"] as const,
  customers: (params?: unknown) => ["customers", params] as const,
  customer: (id: string) => ["customers", id] as const,
  segments: ["segments"] as const,
  segment: (id: string) => ["segments", id] as const,
  countries: ["countries"] as const,
  country: (code: string) => ["countries", code] as const,
  agents: ["agents"] as const,
  agent: (id: string) => ["agents", id] as const,
  flowEdges: ["agents", "flow-edges"] as const,
  governance: (params?: unknown) => ["governance", params] as const,
  guardrails: (params?: unknown) => ["guardrails", params] as const,
  businessRules: (params?: unknown) => ["business-rules", params] as const,
  skills: (params?: unknown) => ["skills", params] as const,
  recommendations: (params?: unknown) => ["recommendations", params] as const,
  analytics: ["analytics"] as const,
  settings: ["settings"] as const,
}
